### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by n123456789k** [marcus-sa/storm-engine#1]
Can't seem to run adonis install on it?

**Comment by marcus-sa** [comment]
Can you provide some error logs?
Adonis will be switched out with https://github.com/marcus-sa/Titan once I get some spare time.

**Comment by n123456789k** [comment]
It just keeps throwing module missing errors.

Can you try do a new install on the committed files you have and do a install tutorial just to make sure I'm not missing anything then I can throw the logs up (it could be me going wrong)

**Comment by marcus-sa** [comment]
What are you on about?
You obviously have to install the modules yourself through `npm install`
